### PR TITLE
Add Better Handling to Ajax Errors

### LINKED ISSUE #87: AJAX Error Handling
When an inevitable Ajax call fails, right now it is just an `alert`.

I'm trying to come up with suggestions where Ajax enabling/disabling of auto-updates fails gracefully.

Any ideas?

### PR DESCRIPTION
**Pull request by ronalfy**
Resolves #87 

This PR adds an inline error message when something fails, whether it's a capabilities check, or some other type of failure.

ajax-error-handling-plugins

themes-error-screen

### CODE REVIEW

**Comment by ronalfy** [comment]
@audrasjb @pbiron 

I combined all the ideas on #87 into this PR. Please weigh in with your comments/feedback.

Thanks!

Ronald Huereca

**Review by audrasjb — APPROVED** [review]
Looks good to me, thanks @ronalfy !

**Comment by ronalfy** [comment]
Here's an example of a generic message which is sent on failure (e.g., nonce failure, timeout):

nonce-failure

**Review by pbiron — APPROVED** [review]
nice work.

**Pull request merged**
