### PR TITLE
Wrong kick off year in readme.txt

### PR DESCRIPTION
**Pull request by knutsp**

### CODE REVIEW

**Comment by audrasjb** [comment]
@knutsp can you please separate the readme fix and the wrapper proposal?

**Comment by knutsp** [comment]
Happened by accident. Let me see if I'm able.

**Comment by knutsp** [comment]
Sorry, this got lost.

**Review by audrasjb — APPROVED** [review]

**Comment by audrasjb** [comment]
Thanks!

**Pull request merged**
